---
title: "diffusion_vessels"
author: "Richard J Beck"
date: "`r Sys.Date()`"
output: html_document
---

Notes: tran.2d does noflux boundaries by default.

Useful functions for converting molar oxygen concentration
```{r}

ml2mmhg <- function(o2,a=0.0031,v=1){
  ## input is amount of o2 in ml
  ## v is the volume o2 is contained in (units mm^3)
  o2 <- o2*100*1000/v # (ml)*(ml/dl)*(mm^3/ml)/(mm^3) = ml/dL
  mmhg <- o2/a 
  return(mmhg)
}


mol2ml <- function(n_o2,r=0.0821,t=310,p=1){
  ## r =  0.0821 L·atm/mol·K
  ## p = 1atm
  ## t = 310K (body temp)
  
  v <- n_o2*r*t/p ## litres
  return(v*1000) ##ml
}



```

Functions for the ODE solver

```{r}

require(ReacTran) 
require(rootSolve) 

pde2D<-function(t,y,parms){ 

  CONC<-matrix(nr=parms['n'],nc=parms['n'],y) 
  Tran<-tran.2D(CONC,D.x=parms['D'],D.y=parms['D'],
                dx=parms['d'], dy=parms['d']) 
  dCONC<-Tran$dC-parms['r']*CONC/(CONC + parms['k50'])
  dCONC[parms['n2'],parms['n2']]<-dCONC[parms['n2'],parms['n2']]+parms['p'] 
  
  return(list(as.vector(dCONC))) }

steady_profile <- function(pars,return="SLICE"){
  pars['n2']<- ceiling(pars['n']/2)
  Conc0<-matrix(nr=pars["n"],nc=pars["n"],0) 
  ST<-steady.2D(y=Conc0,func=pde2D, parms=pars,dimens=c(pars["n"],pars["n"]),lrw=6e+05)
  if(return=="SLICE"){
    res <- matrix(ST$y,nrow=sqrt(length(ST$y)))[pars["n2"],]
    return(res)
  }
  if(return=="IMAGE"){
    image(ST,main="steady-state2-D PDE")
    return(0)
  }
  return(st)
}

evolving_profiles <- function(pars,return_consumption=T){
  # solve for 8 time units
  times <- seq(10,90,10)/2
  Conc0<-matrix(nr=pars["n"],nc=pars["n"],0)
  x <- ode.2D (y = Conc0, func = pde2D, t = times,
               parms=pars,dimens=c(pars["n"],pars["n"]),lrw=6e+05)
  if(return_consumption){
    for(i in 2:ncol(x)) x[,i] <- pars['r']*x[,i]/(x[,i] + pars['k50'])
  }
  return(x)
}

```

Example image of diffusion test setup
```{r}
pars <- c(n=5.100000e+01,d= 2.000000e-02,D= 1.666667e-05,r= 1.000000e+0,p= 2.000000e+03,k50= 2.000000e+03)
x <- evolving_profiles(pars,return_consumption=F)
image(x, ask = FALSE, mfrow = c(3,3), main = paste("time", times))
```

Steady state results with various parameters
```{r}

pp <- expand.grid(sv=c(1,10,50,100,200),
                  p=seq(1,5,2),
                  vk50=c(0.1,1,10))

df <- do.call(rbind,pbapply::pblapply(1:nrow(pp), function(i){
  vk50 <- pp$vk50[i]
  pars <- c(n=51,d=0.02,D=D,r=vk50,p=pp$p[i]*vk50*100,k50=vk50*pp$sv[i])
  df <- data.frame(C=steady_profile(pars,"SLICE"),
            x=20*(1:pars["n"]),
            p=pp$p[i],r=vk50,k50=vk50*pp$sv[i])
  df$consumption <- pars['r']*df$C/(df$C + pars['k50'])
  df
}))


p1 <- ggplot(df,aes(x=x,y=C,group=as.character(k50),color=k50))+
  facet_grid(rows=vars(paste0("R=",r)),cols=vars(paste0("F=",p)),scales="free")+
  geom_line()+
  scale_color_viridis_c(trans="log")
p1
p2 <- ggplot(df,aes(x=x,y=consumption,group=as.character(k50),color=k50))+
  facet_grid(rows=vars(paste0("R=",r)),cols=vars(paste0("F=",p)),scales="free")+
  geom_line()+
  geom_vline(xintercept=(500-150),color="red",lty=2)+
  geom_vline(xintercept=(500+150),color="red",lty=2)+
  scale_color_viridis_c(expression(k[50]),trans="log")
p2
p3 <- ggplot(df,aes(x=x,y=consumption,group=as.character(k50),color=k50/r))+
  facet_grid(rows=vars(paste0("R=",r)),cols=vars(paste0("F=",p)),scales="free")+
  geom_line()+
  geom_vline(xintercept=(500-150),color="red",lty=2)+
  geom_vline(xintercept=(500+150),color="red",lty=2)+
  scale_color_viridis_c(expression(k[50]/R),trans="log")
p3

```


Steady state results with literature derived parameters and comparison with ABM 
```{r}


D <- 1*10^(-5) #cm^2/s
D <- D*100 ##mm^2/s
## assume cell consumes 25amol/cell/second. 

vk50 <- 0.025# fmol/cell/s
vk50 <- 25# amol/cell/s

pars <- c(n=51,d=0.02,D=D,r=vk50,p=vk50*130,k50=vk50/5)
df <- data.frame(C=steady_profile(pars,"SLICE"),
          x=20*(1:pars["n"]-1))
df$consumption <- pars['r']*df$C/(df$C + pars['k50'])

p1 <- ggplot(df,aes(x=x,y=consumption))+
  geom_line()+
  geom_vline(xintercept=(500-150),color="red",lty=2)+
  geom_vline(xintercept=(500+150),color="red",lty=2)+
  scale_y_continuous(expression(consumption~(amol~cell^{-1}~s^{-1})))+
  scale_x_continuous(expression(distance~(mu*m)))
p1

p2 <- ggplot(df,aes(x=x,y=ml2mmhg(mol2ml(C*10^(-18)),v=(0.02^3))))+
  geom_line()+
  geom_vline(xintercept=(500-150),color="red",lty=2)+
  geom_vline(xintercept=(500+150),color="red",lty=2)+
  scale_y_continuous(expression(Concentration~(mmHg)))+
  scale_x_continuous(expression(distance~(mu*m)))
p2

xabm <-  read.table("~/projects/008_birthrateLandscape/ABM_ploidy/output/O2/400-O2Distribution.csv",sep=",")
xabm <- xabm[,101]
xabm <- data.frame(C=xabm,x=1:length(xabm))
xabm$x <- 20*xabm$x
xabm$x <- xabm$x-median(xabm$x)
df$x <- df$x-median(df$x)
p2b <- ggplot(df,aes(x=x,y=ml2mmhg(mol2ml(C*10^(-18)),v=(0.02^3))))+
  geom_line(aes(color="PDE"),size=1)+
  geom_line(data=xabm,aes(color="ABM"))+
  geom_vline(xintercept=(-100),color="red",lty=2)+
  geom_vline(xintercept=(+100),color="red",lty=2)+
  scale_y_continuous(expression(Concentration~(mmHg)))+
  scale_x_continuous(expression(distance~(mu*m)),limits=c(-500,500))+
  scale_color_discrete()
p2b


pars["D"]/(0.02^2)
```



